# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nR85HaEepCLaQQa9PY5IsCYm51Cm7JpL

Tienda en línea ( Dataset country-income.csv)
"""

#importar librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_frame = pd.read_csv('/content/country-income.csv') #Cargar el archivo CSV y guardarlo en una variable. 
data_frame.head(10)

#número de columnas y filas en las cuáles encuentras valores nulos o perdidos y cuántos
columnas  = data_frame.columns.isna() #Obtenemos el estado de cada columna si hay nulo o no
col_null = 0
filas = data_frame.index.isna() #Obtenemos el estado de cada fila si hay nulo o no
fil_null = 0
data_frame.info() #Obtenemos una descripción del dataset
val_null = 0
#Recorremos los resultados de los estados nulos de cada columna y fila, en caso de que alguna sea nulo sumanos 1
for i in columnas:
  if i == 'TRUE':
    col_null+=1
for i in filas:
  if i == 'TRUE':
    fil_null += 1
for i in data_frame.isnull():
  if i == 'TRUE':
    val_null +=1

#mostramos los resultados 
print('Número de columnas con valores nulos: '+ str(col_null))
print('Número de filas con valores nulos: '+str(fil_null))
print('Numero total de valores nulos encontrados: '+str(val_null))
print('Usando métodos: Columnas nulas '+ str(data_frame.columns.isnull().sum())) #Obtenemos las columnas nulas y sumamos 
print('Usando métodos: Filas nulas '+ str(data_frame.index.isnull().sum())) #Obtenemos las filas con valores nulos y sumamos 
print('Usando métodos: Total nulos ' + str(data_frame.isnull().sum().sum())) #Obtenemos una descripción de los valores nulos, los sumamos una vez y quedan por columna, luego sumamos nuevamente para obtener el total de nulos

#Sustituye esos valores perdidos por la media de la columna
data_frame['Age'].fillna(data_frame['Age'].describe()['mean']) #Indicamos la columna sobre la que se va a trabajar, usamos el método llenar nulos y le pasamos como dato la media de dicha columna
data_frame['Income'].fillna(data_frame['Income'].describe()['mean'])
data_frame.head(10)

#Calcula la media, máximo, mínimo y desviación estándar de las columnas con valores numéricos.
data_frame.describe()

#Convierte todos los valores categóricos y binarios en numéricos sin alterar la estructura del dataset.
data_frame = pd.get_dummies(data_frame, columns = ["Region"]) #Convertimos las columnas categoricas a numerícas con el método get_dummies, pasansole el dataframe y la columna a convertir.
data_frame = pd.get_dummies(data_frame, columns = ["Online_Shopper"], drop_first = True) #Realizamos lo mismo que en el anterior pero eliminanos una de las nuevas columnas que se van a generar ya que al ser una columna binaria no necesita especificar lo mismo en la segunda (Si es está en Online_shopper_yes podemos ovbiar que no está en Online_shopper_No, por lo que es innecesario)
data_frame.head()